spring:
  config:
    import:
      optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    default-schema: ${DB_SCHEMA}
    change-log: classpath:db/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    drop-first: false

  session:
    store-type: redis

  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

logging:
  file:
    name: logs/storage.log
  level:
    root: INFO
    com.example.cloud_storage: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH-mm-ss} %-5level %logger{100} - %msg%n"
