spring:
  config:
    import:
      optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    default-schema: ${DB_SCHEMA}
    change-log: classpath:db/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    drop-first: false

logging:
  file:
    name: logs/storage.log
  level:
    root: INFO
    com.example.cloud_storage: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH-mm-ss} %-5level %logger{100} - %msg%n"
